#!/usr/bin/python3

import os
import os.path
import argparse
import sys
import time
import signal
import shutil
import getpass
import contextlib

from typing import Any, Dict, Optional, Sequence, TextIO

import daemon # type: ignore
import daemon.pidfile # type: ignore
from lockfile import AlreadyLocked # type: ignore
from oauthlib.oauth2.rfc6749.errors import OAuth2Error # type: ignore

from oauth2_clientmanager import OAuth2ClientManager
from oauth2_clientmanager import NoTokenError, NoPrivateKeyError

try:
    from contextlib import nullcontext
except ImportError:
    class nullcontext(contextlib.AbstractContextManager):
        def __init__(self, enter_result=None):
            self.enter_result = enter_result

        def __enter__(self):
            return self.enter_result

        def __exit__(self, *excinfo):
            pass

registrations: Dict[str, Dict[str, Sequence[str]]] = {
    # Untested
    # 'google': {
    #     'authorize_endpoint': 'https://accounts.google.com/o/oauth2/auth',
    #     'devicecode_endpoint': 'https://oauth2.googleapis.com/device/code',
    #     'token_endpoint': 'https://accounts.google.com/o/oauth2/token',
    #     'redirect_uri': 'urn:ietf:wg:oauth:2.0:oob',
    #     'imap_endpoint': 'imap.gmail.com',
    #     'pop_endpoint': 'pop.gmail.com',
    #     'smtp_endpoint': 'smtp.gmail.com',
    #     'sasl_method': 'OAUTHBEARER',
    #     'scope': 'https://mail.google.com/',
    # },
    'microsoft': {
        'authorize_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
        'devicecode_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/devicecode',
        'token_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
        #'redirect_uri': 'https://login.microsoftonline.com/common/oauth2/nativeclient',
        'redirect_uri' : 'http://localhost',
        'imap_endpoint': 'outlook.office365.com',
        'pop_endpoint': 'outlook.office365.com',
        'smtp_endpoint': 'smtp.office365.com',
        'sasl_method': 'XOAUTH2',
        'scope': ('offline_access https://outlook.office.com/IMAP.AccessAsUser.All',
                  'https://outlook.office.com/POP.AccessAsUser.All',
                  'https://outlook.office.com/SMTP.Send'),
    },
    'suse-o365': {
        'inherits' : 'microsoft',
        'client_id' : '3ce62cca-417a-462c-bbe5-03d1888daf53',
        'tenant' : 'mysuse.onmicrosoft.com',
        'client_secret' : ''
    }
}
DEFAULT_PROVIDER = 'suse-o365'

def shutdown_listeners_and_exit(oaclient: OAuth2ClientManager) -> None:
    print("Shutting down", file=sys.stderr, flush=True)
    oaclient.stop_file_writer()
    oaclient.stop_socket_listener()
    sys.exit(0)

class SignalHandler:
    def __init__(self, client: OAuth2ClientManager) -> None:
        self.client = client

    def __call__(self, signum: int, trace: Any) -> None:
        shutdown_listeners_and_exit(self.client)

def token_needs_refreshing(token: Dict[str, Any], threshold: int) -> bool:
    return token['expires_at'] + threshold > time.time()

def wait_for_refresh_timeout(oaclient: OAuth2ClientManager, thresh: int) -> None:
    if not oaclient.token:
        raise NoTokenError("No token to refresh")

    timeout = oaclient.access_token_expiry - thresh - time.time()

    if timeout > 0:
        if oaclient.verbose:
            print(f"Waiting {int(timeout)}s to refresh token.", file=sys.stderr)
        time.sleep(timeout)
    else:
        if oaclient.debug:
            print("Token has expired.", file=sys.stderr)

def main_loop(oaclient: OAuth2ClientManager, sockname: Optional[str], filename: Optional[str],
              debug: bool = False, threshold: int = 300) -> None:

    if not oaclient.token:
        raise NoTokenError("No token to monitor")

    if token_needs_refreshing(oaclient.token, threshold):
        oaclient.refresh_token()

    oaclient.save_session()

    if sockname:
        oaclient.start_socket_listener(sockname)

    if filename:
        oaclient.start_file_writer(filename)

    try:
        while True:
            wait_for_refresh_timeout(oaclient, threshold)
            if debug or not sys.stderr.isatty():
                print("Wait for refresh complete", file=sys.stderr, flush=True)
            oaclient.refresh_token()
            oaclient.save_session()

            if debug and not filename and not sockname:
                print("\nBEGIN ACCESS TOKEN")
                if oaclient.token and 'access_token' in oaclient.token:
                    print(oaclient.token['access_token'])
                else:
                    raise NoTokenError("Token was supposed to be refreshed but is missing")
    except KeyboardInterrupt:
        shutdown_listeners_and_exit(oaclient)

def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='increase verbosity')
    parser.add_argument('-d', '--debug', action='store_true',
                        help='enable debug output')
    parser.add_argument('-a', '--authorize', action='store_true',
                        help='generate a new refresh token on startup using the default clientid and secret for the provider')
    parser.add_argument('-c', '--clientid', type=str, default=None,
                        help='specify client id to use for authorization if different than the default (or if there is no default).')
    parser.add_argument('-p', '--port', type=int, default=0,
                        help='specify port for http server (useful for tunneling to remote host)')
    parser.add_argument('-D', '--daemonize', type=str, dest='logfile',
                        help='detach and daemonize after user interaction is complete, logging to file')
    parser.add_argument('-f', '--file', type=str, default=None,
                        help='write access token to <file> (periodically, prior to expiration, if in daemon mode)')
    parser.add_argument('-i', '--pidfile', type=str, default=None, dest='pidfile',
                        help='write daemon pid to <pidfile>')
    parser.add_argument('-s', '--socket', type=str, default=None,
                        help='create a UNIX socket at <socket> with an http listener to provide access token on request')
    parser.add_argument('-P', '--provider', type=str, default=DEFAULT_PROVIDER,
                        choices=registrations.keys(),
                        help=f'provider to request tokens (default={DEFAULT_PROVIDER})')
    parser.add_argument('-q', '--quiet', action='store_true', help='limit unnecessary output')
    parser.add_argument('-t', '--threshold', type=int, default=300,
                        help='threshold before expiration to attempt to refresh tokens. (default=300s)')
    parser.add_argument('--force', action='store_true', help='overwrite sessionfile if it exists')
    parser.add_argument('sessionfile', help='path to store encrypted session and refresh token')
    args = parser.parse_args()
    if args.debug:
        args.verbose = True
    return args

def resolve_registration(provider, loops=None):
    reg = registrations[provider]
    if 'inherits' in reg:
        if loops is None:
            loops = [provider]
        elif provider in loops:
            raise ValueError(f"Provider '{provider}' is already in the dependency chain")
        else:
            loops.append(provider)
        inherited = resolve_registration(reg['inherits'], loops)
        reg = { **inherited, **reg }

    return reg

class FatalError(RuntimeError):
    pass

def main() -> None:
    args = parse_arguments()

    if args.pidfile:
        pidfile_path = os.path.realpath(args.pidfile)
        oa2cd_pidfile = daemon.pidfile.TimeoutPIDLockFile(pidfile_path)
        # If we know the pidfile is there, we can skip asking the user
        # for the password and exit early.  This is racy and for convenience
        # only.  It's checked properly before we start the main loop.
        if oa2cd_pidfile.is_locked():
            pid = oa2cd_pidfile.read_pid()
            raise FatalError(f"PID file {pidfile_path} is already locked by PID {pid}.")
    else:
        oa2cd_pidfile = nullcontext()

    try:
        if args.authorize:
            registration = resolve_registration(args.provider)
            if args.clientid:
                clientid = args.clientid
            elif 'client_id' in registration:
                clientid = registration['client_id']
            else:
                raise FatalError(f"Provider {args.provider} has no default client id set.\nPlease provide one with --clientid.")

            client_data = {
                'client_id' : clientid,
            }

            if os.path.exists(args.sessionfile) and not args.force:
                raise FatalError(f"{args.sessionfile} already exists.")

            # A missing client_secret will cause a password prompt.
            # If the client_secret key is present, even with an empty
            # string or None, we'll use that.
            if 'client_secret' in registration and not args.clientid:
                client_data['client_secret'] = registration['client_secret']
            else:
                try:
                    secret = getpass.getpass(f"Secret for clientid {clientid} (leave empty if there is no secret): ")
                    if secret:
                        client_data['client_secret'] = secret
                except (EOFError, KeyboardInterrupt):
                    raise FatalError("\nFailed to obtain client secret.")

            if 'tenant' in registration:
                client_data['tenant'] = registration['tenant']
            try:
                oaclient = OAuth2ClientManager.from_new_authorization(registration, client_data,
                                                               args.port, debug=args.debug,
                                                               verbose=args.verbose)
            except OAuth2Error as ex:
                print(f"Failed to obtain authorization: {str(ex)}.", file=sys.stderr)
                if args.debug:
                    raise ex from ex
                sys.exit(1)
            oaclient.save_session(args.sessionfile, overwrite=args.force)
        else:
            try:
                # NB: If we make a request before daemonizing, we'll have to
                # re-establish the session afterwards as the sockets backing
                # the connection pool will have been closed.
                oaclient = OAuth2ClientManager.from_saved_session(args.sessionfile,
                                                           debug=args.debug, verbose=args.verbose)
                if not oaclient.token:
                    raise NoTokenError("Session didn't contain valid session.")
            except (FileNotFoundError, PermissionError) as ex:
                raise FatalError(f"Couldn't open session file: {str(ex)}") from ex
    except NoPrivateKeyError as ex:
        raise FatalError(f"\n{str(ex)}") from ex

    if not args.file and not args.socket:
        columns = shutil.get_terminal_size((80, 25))[0]
        if not args.quiet:
            raise FatalError("No file or socket was specified")

        if token_needs_refreshing(oaclient.token, args.threshold):
            oaclient.refresh_token()

        if oaclient.token and 'access_token' in oaclient.token:
            if not args.quiet:
                print("Current access token follows:", file=sys.stderr)
                print(columns * '-', file=sys.stderr)
            print(oaclient.token['access_token'])
            if not args.quiet:
                print(columns * '-', file=sys.stderr)
        else:
            print("No valid access token found.", file=sys.stderr)
        sys.exit(0)

    logfile: Optional[TextIO] = None
    if args.logfile:
        try:
            logfile = open(args.logfile, 'w+') # pylint: disable=consider-using-with
        except (OSError, IOError) as ex:
            raise FatalError(f"Failed to open logfile {logfile}: {ex.args[1]}.") from ex

        context = daemon.DaemonContext(files_preserve=[logfile],
                                       working_directory=os.getcwd(),
                                       pidfile=oa2cd_pidfile,
                                       stdout=sys.stdout,
                                       stderr=sys.stderr)
        context.signal_map = {
            signal.SIGTERM: SignalHandler,
            signal.SIGHUP: 'terminate',
        }
    else:
        context = oa2cd_pidfile

    try:
        with context:
            if logfile:
                sys.stderr.close()
                sys.stdout.close()
                sys.stderr = logfile
                sys.stdout = logfile
            main_loop(oaclient, args.socket, args.file, args.debug, args.threshold)
    except AlreadyLocked as ex:
        raise FatalError(f"{ex} by PID {oa2cd_pidfile.read_pid()}") from ex

if __name__ == '__main__':
    try:
        main()
    except FatalError as ex:
        print(str(ex) + "  Exiting.", file=sys.stderr)
        sys.exit(1)

